*** empty log message ***

diff --git a/LDP/lampadas/configure b/LDP/lampadas/configure
--- a/LDP/lampadas/configure
+++ b/LDP/lampadas/configure
@@ -22,7 +22,11 @@ check()
       return 0
     fi
     echo "No"
-    [ -n "${error}" ] && echo "ERROR: ${error}"
+    if [ -n "${error}" ]; then
+      local type=ERROR
+      [ "${mode}" = "warning" ] && type=WARNING
+      echo "${type}: ${error}"
+    fi
     [ "${mode}" = "exit" ] && exit -1
     [ "${mode}" = "count" ] && CHECK_ERROR=$( expr ${CHECK_ERROR} + 1 )
     return 1
@@ -363,6 +367,13 @@ check_dist_${DIST_NAME} "count"
 for app in iconv m4 make perl sed tar; do
   check_which count ${app}
 done
+
+if ! check_which warning docbook-to-man; then
+  if ! check_which count docbook2man; then
+    echo "ERROR: Neither docbook-to-man nor " \
+    	"docbook2man (package docbook-utils) installed."
+  fi
+fi
 
 check_postgres
 
