Don't know what this is all about. Fixed a lot of bloat, anyway.

diff --git a/LDP/lampadas/bin/lampadasdb b/LDP/lampadas/bin/lampadasdb
--- a/LDP/lampadas/bin/lampadasdb
+++ b/LDP/lampadas/bin/lampadasdb
@@ -26,103 +26,59 @@ Where ACTION is one of:
 "
 }
 
-#---------------------------------------------
-# main()
-
-if [ "$#" = 0 ]; then
-    usage;
-    exit 1
-fi
-
 create()
 {
-	if [ "$DBNAME" = "" ]; then
-		exit 1
-	else
-		echo "Creating $DBNAME"
-		for tab in $SQLDIR/tables/* ; do
-		    psql $DBNAME -qf $tab/create.sql
-		done
-	fi
+	psql $1 -qf "$2/create.sql"
 }
 
 drop()
 {
-	if [ "$DBNAME" = "" ]; then
-		exit 1
-	else
-		echo "Dropping all tables in $DBNAME"
-		for tab in $SQLDIR/tables/* ; do
-		    psql $DBNAME -c 'DROP TABLE $tab;'
-		done 
-	fi
+	psql $1 -c "DROP TABLE $3;"
 }
 
 delete()
 {
-	if [ "$DBNAME" = "" ]; then
-		echo "Deleting $DBNAME"
-		for tab in $SQLDIR/tables/* ; do
-		    psql $DBNAME -c 'DELETE from $tab;'
-		done 
-	fi
+	psql $1 -c "DELETE from $3;"
 }
 
 load()
 {
-	if [ "$DBNAME" = "" ]; then
-		exit 1
-	else
-		echo "Loading $DBNAME"
-		for tab in $SQLDIR/tables/* ; do
-		    psql $DBNAME -c "copy $tab from '/tmp/$tab';"
-		done 
-	fi
+	psql $1 -c "copy $3 from '/tmp/$3';"
 }
 
 save()
 {
-	if [ "$DBNAME" = "" ]; then
-		exit 1
-	else
-		echo "Saving $DBNAME"
-		for tab in $SQLDIR/tables/* ; do
-		    psql $DBNAME -c "copy $tab to '/tmp/$tab';"
-		done 
-	fi
+	echo "Saving $3"
 }
+
+#---------------------------------------------
+# main()
 
 while test $# -gt 0 ; do
     case "${1}" in
 	-h | --help )
-	    COMMAND="usage"; shift ;;
-	create )
-	    COMMAND="create"; shift ;;
-	drop )
-	    COMMAND="drop"; shift ;;
-	delete )
-	    COMMAND="delete"; shift ;;
-	load )
-	    COMMAND="load"; shift ;;
-	save )
-	    COMMAND="save"; shift ;;
-	* )
-	    DBNAME="${1}"; shift ;;
+		usage
+		exit 1
+		;;
+	"usage" | "create" | "drop" | "delete" | "load" | "save" )
+		COMMAND="${1}"
+		shift
+		DBNAME="${1}"
+		break
+		;;
+	*)	echo "Invalid command: ${1}"
+		exit 1
+		;;
     esac
 done
 
-case "$COMMAND" in
-	"usage" )
-		usage;;
-	"create" )
-		create;;
-	"drop" )
-		drop;;
-	"delete" )
-		delete;;
-	"load" )
-		load;;
-	"save" )
-		save;;
-esac
+if [ -z "$COMMAND" -o -z "$DBNAME" ]; then
+ 	usage
+	exit 1
+fi
 
+find $SQLDIR/tables -type d -maxdepth 1 -mindepth 1 ! -name CVS \
+| while read tab
+do
+	"$COMMAND" "$DBNAME" "$tab" $(basename "$tab")
+done 
